### ISSUE TITLE
`Factorial` does not actually save and re-use previous calculations

### ISSUE THREAD

**Issue by nathanaelbosch** [scheinerman/BigCombinatorics.jl#4]
The documentation and README suggest that all implemented functions provide some form of caching. `Factorial` does not:

https://github.com/scheinerman/BigCombinatorics.jl/blob/3106a48c8f5b9c406a94ee5843f7b966f8f5bfea/src/BigCombinatorics.jl#L136-L150

Why is this the case, does caching simply not provide any real benefit for the computation of factorials? 

To resolve this, it would be great to either implement caching, or highlight better in the documentation that `Factorial` does not have the behaviour currently suggested in the README and documentation.

**Comment by scheinerman** [comment]
Hi @nathanaelbosch . In the README file I have this:

>In some cases, the built-in Julia functions with similar names are sufficiently speedy that we don't bother saving the results, but rather simply wrap those functions in ours.

This is the case for `Factorial`. 

It's been years since I worked on this so I don't recall if I did timing tests to see if making a cached version of `Factorial` would have been (significantly) faster.

**Comment by nathanaelbosch** [comment]
Thanks! Completely missed that part in the README but this of course clears the confusion. Thanks again for the fast reply!
